In [1]:
import pandas as pd
# Lee el archivo CSV
data = pd.read_csv("C:\\Users\\lisbeth\\OneDrive\\Escritorio\\PUCP\\TESIS\\DATA\\BASEMATRICULA20_2.csv")
data

,Unnamed: 0,ID persona,Tipo documento,numero_documento,EDAD,SEXO,DEPARTAMENTO,PROVINCIA,DISTRITO,NOMBRE DE CARRERA,...,codigo_carrera_inei,nombre_carrera_inei,periodo_primera_matricula,periodo_ingreso,domicilio_codigo_ubigeo,domicilio_departamento,domicilio_provincia,domicilio_distrito,_merge,matriculado
0,0,821918,DNI,1157935,46,MASCULINO,LIMA,LIMA,LURIGANCHO,ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
1,1,3939951,DNI,4646204,50,FEMENINO,LIMA,LIMA,LOS OLIVOS,PSICOLOGIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
2,2,986421,DNI,7487362,49,FEMENINO,LIMA,LIMA,VILLA EL SALVADOR,ADMINISTRACIÓN DE EMPRESAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
3,3,1410106,DNI,7753375,51,MASCULINO,LIMA,LIMA,SANTIAGO DE SURCO,INGENIERÍA DE REDES Y COMUNICACIONES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
4,4,950637,DNI,8177174,45,FEMENINO,LIMA,LIMA,SAN JUAN DE LURIGANCHO,DERECHO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,7077,3244562,DNI,81667969,22,FEMENINO,LIMA,LIMA,SAN ISIDRO,ECONOMÍA Y FINANZAS,...,341076.0,ECONOMIA Y FINANZAS,2019-1,2019-1,20000.0,CARACAS,,,both,1
7078,7078,3655095,DNI,90064207,20,FEMENINO,LIMA,LIMA,LOS OLIVOS,OBSTETRICIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
7079,7079,2775422,DNI,90064248,22,FEMENINO,LIMA,LIMA,LOS OLIVOS,ECONOMIA Y NEGOCIOS INTERNACIONALES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
7080,7080,1047845,DNI,90596758,21,FEMENINO,LIMA,LIMA,VILLA EL SALVADOR,PSICOLOGÍA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0
7081,7081,960910,DNI,74630407,21,FEMENINO,LIMA,LIMA,LOS OLIVOS,EDUCACIÓN INICIAL,...,NaN,NaN,2018-2,2018-2,140105.0,LIMA,LIMA,CARABAYLLO,both,1

In [2]:
#data2 = data[data['PUNTAJEFINAL'] == 60]
data2 = data

In [4]:
import random

# Generar un número entero aleatorio entre 0 y 500
numero_entero_aleatorio = random.randint(0, 500)

# Convertir el número entero a decimal con dos decimales
valor_aleatorio = numero_entero_aleatorio / 100

print(valor_aleatorio)  # Imprimir el valor aleatorio generado

4.2

In [5]:
data2['ALEA'] = [random.randint(0, 500)/ 100 for _ in range(len(data2))]
data2

,Unnamed: 0,ID persona,Tipo documento,numero_documento,EDAD,SEXO,DEPARTAMENTO,PROVINCIA,DISTRITO,NOMBRE DE CARRERA,...,nombre_carrera_inei,periodo_primera_matricula,periodo_ingreso,domicilio_codigo_ubigeo,domicilio_departamento,domicilio_provincia,domicilio_distrito,_merge,matriculado,ALEA
0,0,821918,DNI,1157935,46,MASCULINO,LIMA,LIMA,LURIGANCHO,ADMINISTRACIÓN Y NEGOCIOS INTERNACIONALES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,3.24
1,1,3939951,DNI,4646204,50,FEMENINO,LIMA,LIMA,LOS OLIVOS,PSICOLOGIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,1.37
2,2,986421,DNI,7487362,49,FEMENINO,LIMA,LIMA,VILLA EL SALVADOR,ADMINISTRACIÓN DE EMPRESAS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,3.93
3,3,1410106,DNI,7753375,51,MASCULINO,LIMA,LIMA,SANTIAGO DE SURCO,INGENIERÍA DE REDES Y COMUNICACIONES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,0.97
4,4,950637,DNI,8177174,45,FEMENINO,LIMA,LIMA,SAN JUAN DE LURIGANCHO,DERECHO,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,2.41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7077,7077,3244562,DNI,81667969,22,FEMENINO,LIMA,LIMA,SAN ISIDRO,ECONOMÍA Y FINANZAS,...,ECONOMIA Y FINANZAS,2019-1,2019-1,20000.0,CARACAS,,,both,1,4.57
7078,7078,3655095,DNI,90064207,20,FEMENINO,LIMA,LIMA,LOS OLIVOS,OBSTETRICIA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,0.12
7079,7079,2775422,DNI,90064248,22,FEMENINO,LIMA,LIMA,LOS OLIVOS,ECONOMIA Y NEGOCIOS INTERNACIONALES,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,0.20
7080,7080,1047845,DNI,90596758,21,FEMENINO,LIMA,LIMA,VILLA EL SALVADOR,PSICOLOGÍA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only,0,1.25
7081,7081,960910,DNI,74630407,21,FEMENINO,LIMA,LIMA,LOS OLIVOS,EDUCACIÓN INICIAL,...,NaN,2018-2,2018-2,140105.0,LIMA,LIMA,CARABAYLLO,both,1,4.09

In [ ]:
# Define una función para aplicar la lógica condicional
# def calcular_puntaje(row):
# if row['CONDICION'] == 'NO SELECCIONADO':
#        return int(row['PUNTAJEFINAL']) - row['ALEA']
#   else:
#       return int(row['PUNTAJEFINAL']) + row['ALEA']
# Aplica la función a cada fila utilizando apply()
#data2['Puntaje_RD'] = data2.apply(calcular_puntaje, axis=1)
#data2

In [ ]:
from rdrobust import rdrobust,rdbwselect,rdplot

In [ ]:
# Define una función para aplicar la lógica condicional
def calcular_puntaje(row):
    if row['PUNTAJEFINAL'] == 60:
        if row['CONDICION'] == 'NO SELECCIONADO':
            return int(row['PUNTAJEFINAL']) - row['ALEA']
        elif row['CONDICION'] == 'SELECCIONADO':
            return int(row['PUNTAJEFINAL']) + row['ALEA']
    else:
        # Cuando el valor de 'PUNTAJEFINAL' es diferente de 60
        return int(row['PUNTAJEFINAL']) + row['ALEA'] if random.choice([True, False]) else int(row['PUNTAJEFINAL']) - row['ALEA']

# Aplica la función a cada fila utilizando apply()
data2['Puntaje_RD'] = data2.apply(calcular_puntaje, axis=1)
data2

In [ ]:
y = data2.matriculado
score = data2.Puntaje_RD 

covars = pd.get_dummies( data2.IES ).astype(int).iloc[:, 1:]
est = rdrobust(y=y, x=score,c=60, covs = covars, all = True)
est

In [ ]:
results = []
results.append(est.coef)

In [ ]:
!pip install bootstrapped

In [ ]:
print(type(y))

In [ ]:
print(type(score))

In [ ]:
import numpy as np
import pandas as pd
import random

# Crear la columna de aleatorización
data2['ALEA'] = [random.randint(0, 500) / 100 for _ in range(len(data2))]

# Definir la función para calcular el valor transformado según las condiciones dadas
def transform_value(row):
    if row['PUNTAJEFINAL'] == 60:
        if row['CONDICION'] == 'NO SELECCIONADO':
            return int(row['PUNTAJEFINAL']) - row['ALEA']
        elif row['CONDICION'] == 'SELECCIONADO':
            return int(row['PUNTAJEFINAL']) + row['ALEA']
    else:
        # Cuando el valor de 'PUNTAJEFINAL' es diferente de 60
        return int(row['PUNTAJEFINAL']) + row['ALEA'] if random.choice([True, False]) else int(row['PUNTAJEFINAL']) - row['ALEA']
# Aplicar la transformación a la columna 'PUNTAJEFINAL'
data2['PUNTAJEFINAL_TRANSFORMADO'] = data2.apply(transform_value, axis=1)

# Definir los datos para la regresión
y = data2['matriculado']
score = data2['PUNTAJEFINAL_TRANSFORMADO']

# Realizar bootstrap para obtener los coeficientes beta
num_bootstrap = 100
beta_samples = []

for i in range(num_bootstrap):
    # Generar una muestra bootstrap aleatoria con reemplazo
    indices_bootstrap = np.random.choice(len(y), size=len(y), replace=True)
    y_bootstrap = y.iloc[indices_bootstrap] if isinstance(y, pd.Series) else y[indices_bootstrap]
    x_bootstrap = score.iloc[indices_bootstrap] if isinstance(score, pd.Series) else score[indices_bootstrap]
    
    # Realizar la regresión en la muestra bootstrap
    
    covars = pd.get_dummies( data2.IES ).astype(int).iloc[:, 1:]
    est_bootstrap = rdrobust(y_bootstrap, x_bootstrap, c=60, covs = covars, all = True)  # Asumiendo que rdrobust es la función que realiza la regresión discontinua
    # Almacenar los coeficientes beta
beta_samples.append(est_bootstrap.coef.values.flatten())

    
# Convertir la lista de betas en un DataFrame de pandas
df_betas = pd.DataFrame(beta_samples, columns=['Beta_' + str(i) for i in range(1, len(beta_samples[0]) + 1)])

# Guardar el DataFrame en un archivo CSV
df_betas.to_csv('betas_bootstrap.csv', index=False)

In [ ]:
# Verificar los métodos y atributos disponibles en el objeto rdrobust_output
print(dir(est))

In [ ]:
df_betas

In [ ]:
import numpy as np
import pandas as pd
import random

# Crear la columna de aleatorización 100 veces
for iteration in range(100):
    # Crear la columna de aleatorización
    data2['ALEA'] = [random.randint(0, 500) / 100 for _ in range(len(data2))]

    # Definir la función para calcular el valor transformado según las condiciones dadas
    def transform_value(row):
        if row['PUNTAJEFINAL'] == 60:
            if row['CONDICION'] == 'NO SELECCIONADO':
                return int(row['PUNTAJEFINAL']) - row['ALEA']
            elif row['CONDICION'] == 'SELECCIONADO':
                return int(row['PUNTAJEFINAL']) + row['ALEA']
        else:
            # Cuando el valor de 'PUNTAJEFINAL' es diferente de 60
            return int(row['PUNTAJEFINAL']) + row['ALEA'] if random.choice([True, False]) else int(row['PUNTAJEFINAL']) - row['ALEA']
    
    # Aplicar la transformación a la columna 'PUNTAJEFINAL' y almacenarla en una nueva columna
    data2['PUNTAJEFINAL_TRANSFORMADO_' + str(iteration)] = data2.apply(transform_value, axis=1)
    
    # Definir los datos para la regresión
    y = data2['matriculado']
    score = data2['PUNTAJEFINAL_TRANSFORMADO_' + str(iteration)]

    # Realizar bootstrap para obtener los coeficientes beta
    num_bootstrap = 100
    beta_samples = []

    for i in range(num_bootstrap):
        # Generar una muestra bootstrap aleatoria con reemplazo
        indices_bootstrap = np.random.choice(len(y), size=len(y), replace=True)
        y_bootstrap = y.iloc[indices_bootstrap] if isinstance(y, pd.Series) else y[indices_bootstrap]
        x_bootstrap = score.iloc[indices_bootstrap] if isinstance(score, pd.Series) else score[indices_bootstrap]

        # Realizar la regresión en la muestra bootstrap
        covars = pd.get_dummies(data2.IES).astype(int).iloc[:, 1:]
        est_bootstrap = rdrobust(y_bootstrap, x_bootstrap, c=60, covs=covars, all=True)  # Asumiendo que rdrobust es la función que realiza la regresión discontinua

        # Almacenar los coeficientes beta
        beta_samples.append(est_bootstrap.coef.values.flatten())

    # Convertir la lista de betas en un DataFrame de pandas
    df_betas = pd.DataFrame(beta_samples, columns=['Beta_' + str(i) for i in range(1, len(beta_samples[0]) + 1)])

    # Guardar el DataFrame en un archivo CSV
    df_betas.to_csv('betas_bootstrap_' + str(iteration) + '.csv', index=False)

In [6]:

import numpy as np
import pandas as pd
import random

# Definir los datos para la regresión
y = data2['matriculado']
score = data2['PUNTAJEFINAL_TRANSFORMADO']

# Realizar bootstrap para obtener los coeficientes beta
num_bootstrap = 100

for iteration in range(num_bootstrap):
    # Crear la columna de aleatorización para esta iteración del bootstrap
    data2['ALEA'] = [random.randint(0, 500) / 100 for _ in range(len(data2))]

    # Definir la función para calcular el valor transformado según las condiciones dadas
    def transform_value(row):
        if row['PUNTAJEFINAL'] == 60:
            if row['CONDICION'] == 'NO SELECCIONADO':
                return int(row['PUNTAJEFINAL']) - row['ALEA']
            elif row['CONDICION'] == 'SELECCIONADO':
                return int(row['PUNTAJEFINAL']) + row['ALEA']
        else:
            # Cuando el valor de 'PUNTAJEFINAL' es diferente de 60
            return int(row['PUNTAJEFINAL']) + row['ALEA'] if random.choice([True, False]) else int(row['PUNTAJEFINAL']) - row['ALEA']
    
    # Aplicar la transformación a la columna 'PUNTAJEFINAL' y almacenarla en una nueva columna
    data2['PUNTAJEFINAL_TRANSFORMADO'] = data2.apply(transform_value, axis=1)

    # Seleccionar los datos para la regresión de esta iteración del bootstrap
    score = data2['PUNTAJEFINAL_TRANSFORMADO']

    beta_samples = []
    
    # Realizar la regresión en la muestra bootstrap
covars = pd.get_dummies(data2.IES).astype(int).iloc[:, 1:]
est_bootstrap = rdrobust(y=y, x=score, c=60, covs=covars, all=True)  # Asumiendo que rdrobust es la función que realiza la regresión discontinua
# Almacenar los coeficientes beta
beta_samples.append(est_bootstrap.coef.values.flatten())

KeyError: 'PUNTAJEFINAL_TRANSFORMADO'